#################################
# Desktop - Basic List of Tasks #
#################################
---

- hosts: localhost
  become: true

##############  PRE-TASKS  ##############
  pre_tasks:
    - name: Add APT keys (from URLs)
      apt_key:
        url: "{{item}}"
      with_items:
          - https://download.sublimetext.com/sublimehq-pub.gpg # Sublime

    - name: Add APT keys(by ids from keyservers)
      apt_key:
        keyserver: "{{item.keyserver}}"
        id: "{{item.id}}"
      with_items: 
        - { keyserver: 'keyserver.ubuntu.com', id: '36A1D7869245C8950F966E92D8576A8BA88D21E9' }

    - name: Add deb
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items: 
        - deb https://download.sublimetext.com/ apt/stable/ # Sublime
        - deb http://typora.io linux/ # Typora'
     
    - name: Add deb
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items: 
        - sudo add-apt-repository ppa:webupd8team/terminix
      when: 
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution == 'Linux Mint'
      
    - name: Add PPA (Ubuntu codeNAMED repos only)
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items: 
        - 'ppa:alexlarsson/flatpak' # Flatpak
        - 'ppa:peterlevi/ppa' # Variety
        - 'ppa:daniruiz/flat-remix' # Flat Remix Icons
      when: ansible_distribution == 'Ubuntu'
        
    - name: Update Package Cache & Set up APT to work with https sources # for Sublime-Text
      package: 
        name: apt-transport-https
        update_cache: true

##############  TASKS  ##############
  tasks:
    - name: Install Snap and Flatpak
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - snapd
        - snapd-login-service
        - flatpak  

    - name: Install Essential Desktop Packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - geary
        - firefox # Browser
        - git
        - sublime-text # view system files
        - tilix # terminal
        - playonlinux
      ignore_errors: true
    
    - name: Install Unsigned (Typora)
      apt: 
        name: typora
        state: latest
        allow_unauthenticated: true

    - name: Install classic Snaps (VScode)
      command: snap install "{{item}}" --classic
      with_items: 
        - vscode
    
    - name: Switch Fn key off by default for Apple keyboard (Ubuntu named)
      command: "{{item}}"
      with_items:
        - echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf
        - sudo update-initramfs -u -k all
      # when: ansible_distribution == "Ubuntu"
      
      # - name: Switch Fn key off by default for Apple keyboard (Inux Mint)
      # command: "{{item}}"
      # with_items:
      #   - echo 2 | sudo tee /sys/module/hid_apple/parameters/fnmode
      # when: ansible_distribution == "Linux Mint"

    - name: Checkout .settings Repository
      git:
        repo: https://github.com/Likivik/Settings.git
        dest: ~/.settings
      become: false #oterwise ~ means root lol


    - name: Create symlink to .bashrc
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      with_items:
        - { src: '~/.settings/.bashrc', dest: '~/.bashrc' }
        - { src: '~/.settings/.dircolors', dest: '~/.dircolors' }
      become: false # #oterwise ~ means root 

####################################
# Possible additions

### in ~/.config
# - autostart folder
# - tilix # terminal emulator (GTK setups)
### Examples/Reminder

##########################
#     UBUNTU FLAVORS     #
##########################
### - name: Install Tweaking Packages (Variety)
    #   package: 
    #     name: "{{item}}"
    #     state: latest
    #   with_items:
    #     - variety

### - name: Get VScode key
    #   shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

    # - name: Get VScode key sign
    #   shell: mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    #   become: true

    # - name: Get VScode add repo
    #   shell: sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    #   become: true

### - name: Install Fira Code Font
    #   command: "{{item}}"
    #   with_items:
    #     - mkdir -p ~/.local/share/fonts
    #     - touch download.sh
    #     - for type in Bold Light Medium Regular Retina; do\n    wget -O ~/.local/share/fonts/FiraCode-${type}.ttf \ \n    "https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-${type}.ttf?raw=true";\ndone
    #     - bash download.sh
    #     - fc-cache -f
### - name: Install wine-stable
    
