---

- hosts: localhost
  become: true

##############  PRE-TASKS  ##############
  pre_tasks:
    - name: Add APT keys (from URLs)
      apt_key:
        url: "{{item}}"
      with_items:
          - https://download.sublimetext.com/sublimehq-pub.gpg # Sublime

    - name: Add APT keys(by ids from keyservers)
      apt_key:
        keyserver: "{{item.keyserver}}"
        id: "{{item.id}}"
      with_items: 
        - { keyserver: 'keyserver.ubuntu.com', id: '36A1D7869245C8950F966E92D8576A8BA88D21E9' }

    - name: Add PPA and deb
      apt_repository:
        repo: "{{item}}"
      with_items: 
        - 'ppa:peterlevi/ppa' # Variety
        - 'ppa:alexlarsson/flatpak' # Flatpak
        - 'ppa:daniruiz/flat-remix' # Flat Remix Icons
        - deb https://download.sublimetext.com/ apt/stable/ # Sublime
        - deb http://typora.io linux/ # Typora
        
        
    - name: Update Package Cache & Set up APT to work with https sources # for Sublime-Text
      package: 
        name: apt-transport-https
        update_cache: true

##############  TASKS  ##############
  tasks:
    - name: Install Snap and Flatpak
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - snapd
        - snapd-login-service
        - flatpak  

    - name: Install Essential Desktop Packages
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - firefox # Browser
        - sublime-text # view system files
    
    - name: Install Typora (unsigned)
      apt: 
        name: typora
        state: latest
      allow_unauthenticated: true
      
    - name: Install Fira Code Font
      command: "{{item}}"
      with_items:
        - mkdir -p ~/.local/share/fonts
        - touch download.sh
        - |
          for type in Bold Light Medium Regular Retina; do
              wget -O ~/.local/share/fonts/FiraCode-${type}.ttf \
              "https://github.com/tonsky/FiraCode/blob/master/distr/ttf/FiraCode-${type}.ttf?raw=true";
          done
        - bash download.sh
        - fc-cache -f
    
    - name: Install Wine
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - wine-stable
        - playonlinux
        - winetricks

     - name: Install --classic Snaps
       command: snap install "{{item}}" --classic
       with_items: 
         - vscode
    
    - name: Switch Fn key off by default for Apple keyboard
      command: echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf

    - name: Checkout Settings/dotfiles Repository
      git:
        repo: https://github.com/Likivik/Settings.git
        dest: ~/.settings
      become: false #oterwise ~ means root lol


####################################
# Possible additions

### in ~/.config
# - autostart folder
# - tilix # terminal emulator (GTK setups)
# - fonts-firacode # beautiful, has ligatures
### Examples/Reminder

#ansible localhost -m apt -a "pkg=git state=latest" --become-user=SomeUser --become-method=su --ask-become-pass

### - name: Install Tweaking Packages (Variety)
    #   package: 
    #     name: "{{item}}"
    #     state: latest
    #   with_items:
    #     - variety

### - name: Get VScode key
    #   shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

    # - name: Get VScode key sign
    #   shell: mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    #   become: true

    # - name: Get VScode add repo
    #   shell: sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    #   become: true
